// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9SzNHEzuoXRYAG_DJh8VxtUisXG7N20U',
    appId: '1:221938369261:web:84dcbbb3d1ec65888682e4',
    messagingSenderId: '221938369261',
    projectId: 'cartify-a8df0',
    authDomain: 'cartify-a8df0.firebaseapp.com',
    storageBucket: 'cartify-a8df0.firebasestorage.app',
    measurementId: 'G-71CJM7QK3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_T1KaiJ9IUpJ0uEfqLtsch-RmFnVKu_I',
    appId: '1:221938369261:android:3582a95f0bce1b578682e4',
    messagingSenderId: '221938369261',
    projectId: 'cartify-a8df0',
    storageBucket: 'cartify-a8df0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvFc4TuhjeuUDnqQ8sZ10GJ3WMUxljhPo',
    appId: '1:221938369261:ios:407bfe0942e2527f8682e4',
    messagingSenderId: '221938369261',
    projectId: 'cartify-a8df0',
    storageBucket: 'cartify-a8df0.firebasestorage.app',
    iosBundleId: 'com.example.cartify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvFc4TuhjeuUDnqQ8sZ10GJ3WMUxljhPo',
    appId: '1:221938369261:ios:407bfe0942e2527f8682e4',
    messagingSenderId: '221938369261',
    projectId: 'cartify-a8df0',
    storageBucket: 'cartify-a8df0.firebasestorage.app',
    iosBundleId: 'com.example.cartify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9SzNHEzuoXRYAG_DJh8VxtUisXG7N20U',
    appId: '1:221938369261:web:72e4dd3b167bd0158682e4',
    messagingSenderId: '221938369261',
    projectId: 'cartify-a8df0',
    authDomain: 'cartify-a8df0.firebaseapp.com',
    storageBucket: 'cartify-a8df0.firebasestorage.app',
    measurementId: 'G-H5MMWC5NTD',
  );
}
